name: Build Tagtool
run-name: ${{ github.actor }} Running Tagtool build.
on: [push]
jobs:
  build-tagtool:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      BUILDKIT_PROGRESS: plain
      IMAGE_NAME: tjsrowe/prisma-generic
      PRISMA_IMAGE: tjsrowe/prisma-generic:${{ github.sha }}

    steps:
    - name: Check out repositofy code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master

    - name: Install jq
      run: sudo apt-get install jq

    - name: Get the current version of Prisma
      id: get-prisma-version
      run: |
        PRISMA_VERSION=$(jq -r '.. | objects | select(has("node_modules/prisma")) | ."node_modules/prisma".version' package-lock.json)
        echo "PRISMA_VERSION=$PRISMA_VERSION" >> $GITHUB_OUTPUT

    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-single-buildx
        restore-keys: |
          ${{ runner.os }}-single-buildx

    - name: Login to Amazon ECR Public
      id: login-ecr-public
      if: ${{ github.actor != 'dependabot[bot]' }}
      uses: aws-actions/amazon-ecr-login@v2
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
      with:
        registry-type: public

    - name: Build prisma image
      uses: docker/build-push-action@v6
      with:
        context: .
        builder: ${{ steps.buildx.outputs.name }}
        file: Dockerfile
        push: ${{ github.actor != 'dependabot[bot]' }}
        tags: |
          ${{ github.actor != 'dependabot[bot]' && format('{0}/', steps.login-ecr-public.outputs.registry) || ''}}${{ env.PRISMA_IMAGE }}
          ${{ github.actor != 'dependabot[bot]' && format('{0}/', steps.login-ecr-public.outputs.registry) || ''}}${{ env.IMAGE_NAME }}:${{ steps.get-prisma-version.outputs.PRISMA_VERSION }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
